package cardindex.dojocardindex.UserConsentHistory.model;

public enum ConsentHistoryAction {
    CREATED,
    ACCEPTED_BY_USER,
    PARENT_INVITED,
    PARENT_INVITATION_FAILED,
    PARENT_CONFIRMED,
    PARENT_CONSENT_TOKEN_REGENERATED,
    PARENT_CONFIRMATION_MAIL_FAILED,
    PENDING_SET,
    PENDING_CLEARED,
    CANCELED_BY_PARENT_REQUEST,
    CANCELED_BY_USER,
    CANCELED_BY_ADMIN,
    CANCELLATION_CONFIRMATION_MAIL_FAILED,
    RECONSENTED
}
